app/users/models.py
import jwt
from hashlib import md5
from datetime import datetime
from dateutil import tz
from time import time
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask import current_app

from app import db, login

followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
)


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)

    posts = db.relationship('Post', backref='author', lazy='dynamic')
    followed = db.relationship('User',
                               secondary=followers,
                               primaryjoin=(followers.c.follower_id == id),
                               secondaryjoin=(followers.c.followed_id == id),
                               backref=db.backref('followers', lazy='dynamic'),
                               lazy='dynamic')

    def __repr__(self):
        return f"<User {self.username}>"

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        email_hash = md5(self.email.lower().encode('utf-8')).hexdigest()
        return f"https://www.gravatar.com/avatar/{email_hash}?d=identicon&s{size}"

    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count() > 0

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def get_actual_posts(self):
        followed_posts = Post.query.join(
            followers, (followers.c.followed_id == Post.user_id)
        ).filter(followers.c.follower_id == self.id)
        own_posts = Post.query.filter_by(user_id=self.id)
        return followed_posts.union(own_posts).order_by(Post.timestamp.desc())

    def get_reset_password_token(self, expires_in: int = 600) -> str:
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'],
            algorithm='HS256'
        )

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id_ = jwt.decode(token,
                             current_app.config['SECRET_KEY'],
                             algorithms=['HS256']
                             )['reset_password']
        except jwt.DecodeError:
            return
        return User.query.get(id_)

    @property
    def user_last_seen(self):
        from_zone, to_zone = tz.tzutc(), tz.tzlocal()
        utc = self.last_seen.strftime('%d-%m-%Y %H:%M')
        utc = datetime.strptime(utc, '%d-%m-%Y %H:%M')
        utc = utc.replace(tzinfo=from_zone)
        current_user_timestamp = utc.astimezone(to_zone)
        return current_user_timestamp.strftime('%d-%m-%Y %H:%M')


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"<Post {self.body}>"


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, Length

from app.users.models import User


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username')

app/users/__init__.py
from flask import Blueprint

from app.utils import update_user_status

users_bp = Blueprint('users', __name__)


@users_bp.before_request
def update_status():
    update_user_status()


from app.users import routes, models

app/users/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app as app
from flask_login import current_user, login_required

from app import db
from app.users import users_bp
from app.users.forms import EditProfileForm
from app.users.models import Post, User


@users_bp.route('/user/<string:username>')
@login_required
def user_page(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False
    )
    next_url = url_for('users.user_page', username=user.username, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('users.user_page', username=user.username, page=posts.prev_num) \
        if posts.has_prev else None

    return render_template('users/user.jinja2',
                           user=user,
                           posts=posts.items,
                           next_url=next_url,
                           prev_url=prev_url)


@users_bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Changes have been saved.')
        return redirect(url_for('users.user_page', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('users/edit_profile.jinja2', title='Edit Profile', form=form)


@users_bp.route('/follow/<string:username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(f'User {username} not found.')
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('users.user_page', username=username))
    current_user.follow(user)
    db.session.commit()
    flash(f'You are following {username}!')
    return redirect(url_for('users.user_page', username=username))


@users_bp.route('/unfollow/<string:username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(f'User {username} not found.')
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('users.user_page', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(f'You are not following {username}.')
    return redirect(url_for('users.user_page', username=username))

app/templates/users/edit_profile.jinja2
{% extends "base.jinja2" %}

{% block content %}
    {% include "_nav.jinja2" %}
    <div class="form-wrapper">
        <form action="" method="post" class="auth" id="edit-form">
            <h1>Edit Profile</h1>
            {{ form.hidden_tag() }}
            <p class="username">
                {{ form.username.label }}<br>
                {{ form.username(size=32) }}
                {% for error in form.username.errors %}
                    <span style="color: red">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p class="about-me">
                {{ form.about_me.label }}<br>
                {{ form.about_me(cols=50, rows=4) }}
                {% for error in form.about_me.errors %}
                    <span style="color: red">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p class="form-button">{{ form.submit() }}</p>
        </form>
    </div>
{% endblock %}

app/templates/users/user.jinja2
{% extends "base.jinja2" %}

{% block content %}
    {% include "_nav.jinja2" %}
    <div id="user-profile">
        <img class="div1" src="{{ user.avatar(200) }}" alt=" ">
        <div id="user-header"><h1>{{ user.username }}</h1></div>
        {% if user.about_me %}
            <div id="description">{{ user.about_me }}</div>
        {% endif %}
        {% if user.last_seen %}
            <div id="last-seen">Last online: {{ user.user_last_seen }}</div>
        {% endif %}
        <div id="user-stats">{{ user.followers.count() }} followers<br> {{ user.followed.count() }} following.</div>
        {% if user == current_user %}
            <div class="option"><a href="{{ url_for('users.edit_profile') }}">Edit profile</a></div>
        {% elif not current_user.is_following(user) %}
            <div class="option"><a href="{{ url_for('users.follow', username=user.username) }}">Follow&emsp;&#9825;</a>
            </div>
        {% else %}
            <div class="option"><a href="{{ url_for('users.unfollow', username=user.username) }}">Unfollow &#10084;</a>
            </div>
        {% endif %}
    </div>

    {% include "_posts.jinja2" %}
{% endblock %}